config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :user, only: [:new, :create]
  resources :sessions, only: [:new, :create]
  delete :logout, to: "sessions#logout"
  post :search_items, to: "search_items#create"
  get :search_items, to: "search_items#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/search_item.rb
class SearchItem < ApplicationRecord
  belongs_to :user
  before_save :capitalize_text

  validates :text, presence: true,
                   length: { minimum: 3, maximum: 200, message: 'Text must be between 3 and 200 characters' }
  validates :rank, presence: true,
                   numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validate :text_must_be_a_question

  # Remove whitespace and capitalize text
  def capitalize_text
    self.text = text.strip.capitalize
  end

  def text_must_be_a_question
    errors.add(:text, 'Text must be a question') if text.present? && !text.strip.end_with?('?')
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :search_items, dependent: :destroy
  before_save :capitalize_name

  validates :username, presence: true, uniqueness: true, length: { minimum: 3, maximum: 20 }

  # Remove whitespace and capitalize name
  def capitalize_name
    self.username = username.strip.capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern
  extend ActiveSupport::Concern

  included do
    before_action :set_current_user
  end

  def set_current_user
    @current_user = User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/search_items_controller.rb
class SearchItemsController < ApplicationController
  include CurrentUserConcern

  def new
    @search_item = SearchItem.new
  end

  def create
    if params[:text].present? && params[:text].end_with?('?')
      if search_item_exists?
        @search_item = SearchItem.all.where(user: @current_user)
          .where(text: search_item_params[:text].strip.capitalize).first
        @search_item.update(rank: @search_item.rank + 1)
      else
        @search_item = SearchItem.new(search_item_params)
        @search_item.user_id = @current_user.id
        @search_item.save
      end
    else
      auto_search
    end
  end

  def search_item_params
    params.permit(:text)
  end

  # check if the search item already exists
  def search_item_exists?
    SearchItem.all.where(user: @current_user).where(text: search_item_params[:text].strip.capitalize).exists?
  end

  def auto_search
    if params[:text].present?
      text = params[:text].strip.capitalize
      @search_items = SearchItem.all.where(user: @current_user).where('text LIKE ?', "%#{text}%").order(rank: :desc)
    else
      @search_items = []
    end
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.update('search_results', partial: 'search_items/search_results',
                                                                   locals: { search_items: @search_items })
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    username = session_params[:username].strip.capitalize
    @user = User.find_by(username:)

    if @user
      session[:user_id] = @user.id
      redirect_to search_items_path, notice: 'Logged in!'
    else
      redirect_to new_session_path, alert: 'User not found!'
    end
  end

  def logout
    reset_session
    redirect_to new_session_path, notice: 'Logged out!'
  end

  private

  def session_params
    params.require(:user).permit(:username)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to new_session_path, notice: 'User successfully created.'
    else
      render :new, status: :unprocessable_entity, alert: 'User is not able to created.'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_item_helper.rb
module SearchItemHelper
end

app/helpers/search_items_helper.rb
module SearchItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<h1>Home page</h1>

<div class="home_nav">
  <%= link_to 'LOG IN', new_session_path, class: 'btn btn-login' %>
  <%= link_to 'SIGN UP', new_user_path, class: 'btn btn-signup' %>
</div>

app/views/layouts/_alert.html.erb
<% if notice&.present? %>
  <div class="notice" role="alert">
    <i class="fa-regular fa-circle-check icon-success" ></i>
    <%= notice %>
  </div>
<% end %>
<% if alert&.present? %>
  <div class="alert" role="alert">
    <i class="fa-solid fa-circle-exclamation icon-warning"></i>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OrangeJuiceTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <div class="header">
        <h1><span class="main-title">HelpJuice</span><span class="sub-title">Test</span></h1>
        <% if @current_user %>
          <%=  button_to "Logout", logout_path, method: :delete, class: 'logout'  %>
        <%  end %>
      </div>
      <%= render "layouts/alert" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/search_items/_search_form.html.erb
<div class="form-container">
  <%= form_with url: search_items_path, method: :post do |f| %>
    <div class="search-form">
      <%= f.label :text %>
      <%= f.text_field :text, value: params[:text], oninput: "this.form.requestSubmit()", placeholder: "Search", class: "search-form__input" %>
      <%= f.submit "Search", class: "search-form__button", name: "commit", value: "Search" %>
    </div>
  <% end %>

  <div id="search_results"></div>
</div>

app/views/search_items/_search_results.html.erb
<% search_items.each do |items| %>
  <br>
  <%= link_to items.text, '' %>
<% end %>

app/views/search_items/new.html.erb
<%= render "search_items/search_form" %>

app/views/user/new.html.erb
<%= form_for @user, method: :post, url: user_index_path, data: { turbo: false} do |f| %>
  <div class="form-group">
    <div class="form-group__field">
      <div class="user-profile">
        <%= image_tag "https://cdn.icon-icons.com/icons2/1378/PNG/512/avatardefault_92824.png", class: "img" %>
        <p>Upload Picture</p>
      </div>
    </div>
    <div class="form-group__field form-group__input-container">
      <%= f.label :username %>
      <%= f.text_field :username, class: "form-group__field--input", autofocus:true, required:true, autocomplete: true, placeholder: "Userame"%>
    </div>
    <%= f.submit "Register", class: "submit-btn" %>
    <%= link_to "Login", new_session_path, class: "nav-btn" %>
  </div>
<% end %>

app/views/user/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>